name: Terraform CI

on:
  push:
    branches:
      - feature/task3.2.4

jobs:
  terraform:
    name: Terraform Checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
